services:
  configserver:
    image: tihamers/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - serviceBank

  accounts:
    image: tihamers/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - serviceBank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/


  loans:
    image: tihamers/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - serviceBank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: tihamers/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - serviceBank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/


networks:
  serviceBank: